DO $$
BEGIN
CREATE ROLE manager WITH
    LOGIN
    SUPERUSER
    INHERIT
    CREATEDB
    CREATEROLE
    REPLICATION;
EXCEPTION WHEN duplicate_object THEN RAISE NOTICE '%, skipping', SQLERRM USING ERRCODE = SQLSTATE;
END
$$;

CREATE DATABASE audit;
GRANT ALL PRIVILEGES ON DATABASE audit TO manager;

\c audit;

CREATE SCHEMA audit;