# APP_ROOT/docker-compose.yml
#         user-service/docker/db/ddl/init.sql
#         user-service/docker/db/db.Dockerfile
#         user-service/docker/app/app.Dockerfile
#         audit-service/docker/db/ddl/init.sql
#         audit-service/docker/db/db.Dockerfile
#         audit-service/docker/app/app.Dockerfile
#         task-service/docker/db/ddl/init.sql
#         task-service/docker/db/db.Dockerfile
#         task-service/docker/app/app.Dockerfile
version: '3.5'

services:

  audit_service_db:
    build:
      context: ./audit-service/docker/db
      dockerfile: db.Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: manager
      POSTGRES_PASSWORD: manager
    networks:
      - taskmanager_ntwrk

  task_service_db:
    build:
      context: ./task-service/docker/db
      dockerfile: db.Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: manager
      POSTGRES_PASSWORD: manager
    networks:
      - taskmanager_ntwrk

  user_service_db:
    build:
      context: ./user-service/docker/db
      dockerfile: db.Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: manager
      POSTGRES_PASSWORD: manager
    networks:
      - taskmanager_ntwrk

  pgadmin:
    build: pgadmin
    image: taskmanager_pgadmin:1.0.0
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: manager@gmail.com
      PGADMIN_DEFAULT_PASSWORD: manager
    ports:
      - "82:80"
    networks:
      - taskmanager_ntwrk

  user_service_app:
    build:
      dockerfile: user-service/docker/app/app.Dockerfile
    restart: unless-stopped
    ports:
      - "5000:80"
    networks:
      - taskmanager_ntwrk

  audit_service_app:
    build:
      dockerfile: audit-service/docker/app/app.Dockerfile
    restart: unless-stopped
    ports:
      - "5000:81"
    networks:
      - taskmanager_ntwrk

  task_service_app:
    build:
      dockerfile: task-service/docker/app/app.Dockerfile
    restart: unless-stopped
    ports:
      - "5000:82"
    networks:
      - taskmanager_ntwrk

  swagger-ui:
    build: swagger-ui
    image: taskmanager_swagger-ui:1.0.0
    ports:
      - "81:8080"
    networks:
      - taskmanager_ntwrk

networks:
  taskmanager_ntwrk:
    name: taskmanager_ntwrk