spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://web_db:5432/comment?ApplicationName=users-app
    username: users-manager
    password: users-manager
    hikari:
      maximum-pool-size: 6
      minimum-idle: 3
  freemarker:
    check-template-location: false
  jpa:
    open-in-view: false

server:
  port: 80

jwt:
  key: 1e9068186b10235bbd158a95e046e7a5edabf79725cacdfd48241d604fdeb3e4