# APP_ROOT/docker-compose.yml
#         /docker/db/ddl/init.sql
#         /docker/db/db.Dockerfile
#         /docker/app/app.Dockerfile
version: '3.4'

services:

  web_db:
    build:
      context: ./docker/db
      dockerfile: db.Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: manager
      POSTGRES_PASSWORD: manager

  pg_db:
    image: dpage/pgadmin4:7.4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: manager@gmail.com
      PGADMIN_DEFAULT_PASSWORD: manager
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    ports:
      - "5001:80"
    links:
      - web_db

  app:
    build:
      dockerfile: docker/app/app.Dockerfile
    restart: unless-stopped
    ports:
      - "5000:80"
    links:
      - web_db